# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('qkd-v6-example', ['qkd-v6'])
    obj.source = 'qkd-v6-example.cc'

